### ISSUE TITLE
Support for babylonjs

### ISSUE THREAD

**Issue by youlinaa** [codeagent/fft-2d#5]
Very awesome project, do you have any plans for the next step to support babylonjs, I am very, very looking forward to it, thank you very much for the construction of the ocean effect!

**Comment by codeagent** [comment]
I really had a great plans for porting it to treejs and babylonJS as soon as project will be complete.
But for now i don't have mush time to complete the project.
Had you seen babylon alternative? https://playground.babylonjs.com/#YX6IB8#229

**Comment by youlinaa** [comment]
Yes, I have paid attention to it a year ago. It is great, but it needs the support of webgpu. Although the 112 version of chrome already supports it, it still has certain restrictions on users. Expect this webgl version to support babylonjs in the near future.
